export enum CategoriaCampo {
  PACIENTE = "PACIENTE",
  PROFISSIONAL = "PROFISSIONAL",
  ANAMNESE = "ANAMNESE",
  PRONTUARIO = "PRONTUARIO",
  AGENDAMENTO = "AGENDAMENTO",
  FINANCEIRO = "FINANCEIRO",
  RELATORIO = "RELATORIO"
} 