export enum FormaPagamentoClinica {
  PIX = "PIX",
  BOLETO = "BOLETO",
  CARTAO_CREDITO = "CARTAO_CREDITO",
  CARTAO_DEBITO = "CARTAO_DEBITO",
  TRANSFERENCIA = "TRANSFERENCIA",
  DINHEIRO = "DINHEIRO"
} 