export enum NivelBloqueio {
  SEM_BLOQUEIO = "SEM_BLOQUEIO",
  NOTIFICACAO = "NOTIFICACAO",
  AVISO_TOPO = "AVISO_TOPO",
  RESTRICAO_FUNCIONALIDADES = "RESTRICAO_FUNCIONALIDADES",
  BLOQUEIO_TOTAL = "BLOQUEIO_TOTAL"
} 