export enum TipoProntuario {
  CONSULTA = "CONSULTA",
  RETORNO = "RETORNO",
  EXAME = "EXAME",
  PROCEDIMENTO = "PROCEDIMENTO",
  DOCUMENTO = "DOCUMENTO",
  AVALIACAO = "AVALIACAO",
  SESSAO = "SESSAO",
  RELATORIO = "RELATORIO",
  EVOLUCAO = "EVOLUCAO",
  PRESCRICAO = "PRESCRICAO"
} 